# Generated by Django 4.2.8 on 2023-12-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_receipt_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='item_list',
            field=models.TextField(default='item_list', max_length=500),
        ),
    ]
