# Generated by Django 4.2.8 on 2023-12-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_receipt_item_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='item_list',
            field=models.TextField(max_length=500),
        ),
    ]
