# Generated by Django 4.2.8 on 2023-12-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0004_alter_receipt_item_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='store_name',
            field=models.TextField(default='walmart', max_length=250),
        ),
    ]
