# Generated by Django 4.2.8 on 2023-12-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0005_receipt_store_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='store_name',
            field=models.TextField(max_length=250),
        ),
    ]
